name: firebase_calendar
description: Calendário Firebase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
